name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Apply manifests
        run: kubectl apply -R -f k8s/

      - name: Pin image to SHA and rollout
        env:
          SHORT_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          # <<< SET THESE FOR THIS REPO >>>
          DEPLOYMENT_NAME=backend-deployment-userdata  # e.g., backend-deployment-userdata
          CONTAINER_NAME=backend-userdata     # e.g., userdata

          SHORT=${SHORT_SHA:0:7}
          kubectl set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$IMAGE_REPO:sha-$SHORT
          kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s

  # dast-scan:
  #   runs-on: self-hosted
  #   needs: deploy
  #   permissions:
  #     issues: write
  #     contents: read
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Docker login
  #     run: |
  #       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #   - name: Pre-pull ZAP Docker image
  #     run: docker pull ghcr.io/zaproxy/zaproxy:stable

  #   - name: Run OWASP ZAP Full Scan
  #     uses: zaproxy/action-full-scan@v0.5.0
  #     continue-on-error: true
  #     with:
  #       target: ${{ secrets.TARGET_URL }}
  #       docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
  #       artifact_name: zap-scan-report 

