name: CI/CD

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  # 1) Build & push on GitHub-hosted runner
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.meta.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - id: meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        env:
          SHORT_SHA: ${{ steps.meta.outputs.short_sha }}
        run: |
          docker build -t "$IMAGE_NAME:sha-$SHORT_SHA" -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME:sha-$SHORT_SHA"
          docker push "$IMAGE_NAME:latest"
  # 2) Rollout on your self-hosted runner — deploy the SHA tag
  rollout:
    runs-on: [self-hosted, linux, X64]
    needs: build-and-push
    steps:
      - name: Rollout immutable image to cluster
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          SHORT_SHA: ${{ needs.build-and-push.outputs.short_sha }}
        run: |
          DEPLOYMENT_NAME=backend-deployment-userdata
          CONTAINER_NAME=backend-userdata
          kubectl set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$IMAGE_NAME:sha-$SHORT_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s

