name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.meta.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - id: meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        env:
          SHORT_SHA: ${{ steps.meta.outputs.short_sha }}
        run: |
          docker build -t "$IMAGE_NAME:sha-$SHORT_SHA" -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME:sha-$SHORT_SHA"
          docker push "$IMAGE_NAME:latest"